### ISSUE TITLE
Blog post question

### ISSUE THREAD

**Issue by ghost** [Billith/billith.github.io#1]
Sorry if this isn't the right place to ask - I wasn't sure of the proper way to ask a question.

Regarding your writeup for HTB Business CTF 2022 Breakout you mentioned you used IDA. I was wondering if you use the free version? I tried using Ghidra but didn't get to the answer. Unfortunately I deleted the binary so can just try the free version to see if it gives the result that you posted.

**Comment by Billith** [comment]
No worries. I used IDA Pro, however you should be able to get similar pseudo code with IDA Free and cloud decompiler. Regarding Ghidra, I just checked and the flag is there, but I guess Ghidra does not handle stack strings that well, even if you retype the variable to `char[]`

![image](https://user-images.githubusercontent.com/23652438/182149005-66f97661-926d-4bea-bb83-700d113e6da9.png)

You could decode it manually or look for some tooling to automate it

![image](https://user-images.githubusercontent.com/23652438/182150693-833afc7e-9910-45aa-8cb9-70902a086962.png)

**Comment by ghost** [comment]
Thanks very much :) I'll keep IDA Free for future use and make a note of how you decoded the stack string
